export const CONDUCTORES_ALAMEDA = [
  {
    id: 1,
    name: 'Humberto Zapata',
    nameMaps: 'Humberto Zapata',
    tipoVehiculo: 'CARRO',
    phone: '3116111869',
  },
  {
    id: 2,
    name: 'Humberto Montoya',
    nameMaps: 'Humberto Montoya',
    tipoVehiculo: 'CARRO',
    phone: '3044113707',
  },
  {
    id: 3,
    name: 'Luis Enrique Henao',
    nameMaps: 'Luis Enrique Henao',
    tipoVehiculo: 'CARRO',
    phone: '3218126905',
  },
  {
    id: 4,
    name: 'Carlos Monsalve',
    nameMaps: 'Carlos Monsalve',
    tipoVehiculo: 'CARRO',
    phone: '3128996758',
  },
  {
    id: 5,
    name: 'Joaquin Orozco',
    nameMaps: 'Joaquin Orozco',
    tipoVehiculo: 'CARRO',
    phone: '3117126764',
  },
  {
    id: 6,
    name: 'Duvan Agudelo',
    nameMaps: 'Duvan Agudelo',
    tipoVehiculo: 'CARRO',
    phone: '3117071945',
  },
  {
    id: 7,
    name: 'Sebastian Zuluaga',
    nameMaps: 'Sebastian Zuluaga',
    tipoVehiculo: 'CARRO',
    phone: '3226150122',
  },
  {
    id: 8,
    name: 'Giovanni Polania',
    nameMaps: 'Giovanni Polania',
    tipoVehiculo: 'CARRO',
    phone: '3123706659',
  },
  {
    id: 9,
    name: 'Jhon Gutierrez',
    nameMaps: 'Jhon Faber Gutierrez',
    tipoVehiculo: 'CARRO',
    phone: '3225198963',
  },
  {
    id: 10,
    name: 'Favio Rendon',
    nameMaps: 'Favio Rendon',
    tipoVehiculo: 'CARRO',
    phone: '3116049252',
  },
  {
    id: 11,
    name: 'Luis David Zuluaga',
    nameMaps: 'Luis David Zuluaga',
    tipoVehiculo: 'MOTO',
    phone: '3197812806',
  },
  {
    id: 12,
    name: 'Fabian Moreno',
    nameMaps: 'Fabian Moreno',
    tipoVehiculo: 'MOTO',
    phone: '3145574326',
  },
  {
    id: 13,
    name: 'Gilberto Mejia',
    nameMaps: 'Gilberto Mejia',
    tipoVehiculo: 'MOTO',
    phone: '3046111622',
  },
  {
    id: 14,
    name: 'Leonardo Guzman',
    nameMaps: 'Leonardo Guzman',
    tipoVehiculo: 'MOTO',
    phone: '3006405519',
  },
  {
    id: 15,
    name: 'Jhon Ever Martinez',
    nameMaps: 'Jhon Ever Martinez',
    tipoVehiculo: 'MOTO',
    phone: '3142818635',
  },
  {
    id: 16,
    name: 'Jhon Jairo Cardona',
    nameMaps: 'Jhon Jairo Cardona',
    tipoVehiculo: 'MOTO',
    phone: '3143993084',
  },
  {
    id: 17,
    name: 'Yesid Obando',
    nameMaps: 'Yesid Obando',
    tipoVehiculo: 'CARRO',
    phone: '3113469461',
  },
  {
    id: 18,
    name: 'Jesus Navarro',
    nameMaps: 'Jesus Navarro',
    tipoVehiculo: 'CARRO',
    phone: '3113571497',
  },
  {
    id: 19,
    name: 'Hector Giovanni Avila',
    nameMaps: 'Hector Giovanni Avila',
    tipoVehiculo: 'MOTO',
    phone: '3215663479',
  },
  {
    id: 20,
    name: 'Leonardo Tabares',
    nameMaps: 'Leonardo Tabares',
    tipoVehiculo: 'MOTO',
    phone: '3114551250',
  },
  {
    id: 21,
    name: 'Daniel Torres',
    nameMaps: 'Daniel Torres',
    tipoVehiculo: 'MOTO',
    phone: '3105961979',
  },
  {
    id: 22,
    name: 'Jhon Jairo Garzon',
    nameMaps: 'Jhon Jairo Garzon',
    tipoVehiculo: 'MOTO',
    phone: '3168017152',
  },
  {
    id: 23,
    name: 'Juliana Molano',
    nameMaps: 'Juliana Molano',
    tipoVehiculo: 'CARRO',
    phone: '3113840359',
  },
  {
    id: 24,
    name: 'Diego Arango',
    nameMaps: 'Diego Arango',
    tipoVehiculo: 'CARRO',
    phone: '3155635400',
  },
  {
    id: 25,
    name: 'Sergio Gil',
    nameMaps: 'Sergio Gil',
    tipoVehiculo: 'MOTO',
    phone: '3155955015',
  },
  {
    id: 26,
    name: 'Fabio Henao',
    nameMaps: 'Fabio Henao',
    tipoVehiculo: 'MOTO',
    phone: '3014004793',
  },
  {
    id: 27,
    name: 'Juan David Vasquez',
    nameMaps: 'David Labrador',
    tipoVehiculo: 'CARRO',
    phone: '3146977415',
  },
];
