export const CONDUCTORES_GUADALUPE = [
  {
    id: 28,
    name: 'Albeiro Agudelo Torres',
    nameMaps: 'Albeiro Agudelo Torres',
    tipoVehiculo: 'Carro',
    phone: '3136140116',
  },
  {
    id: 29,
    name: 'Alexander Castro Gallego',
    nameMaps: 'Alexander Castro Gallego',
    tipoVehiculo: 'Moto',
    phone: '3154536750',
  },
  {
    id: 30,
    name: 'Andres Muñoz Diez',
    nameMaps: 'Andres Muñoz Diez',
    tipoVehiculo: 'Carro',
    phone: '3206587815',
  },
  {
    id: 31,
    name: 'Carolina Gutierrez Zapata',
    nameMaps: 'Carolina Gutierrez Zapata',
    tipoVehiculo: 'Moto',
    phone: '302 2183949',
  },
  {
    id: 32,
    name: 'Esteban Valencia Galvis',
    nameMaps: 'Esteban Valencia Galvis',
    tipoVehiculo: 'Moto',
    phone: '304 6496301',
  },
  {
    id: 33,
    name: 'Jhon Jairo Acosta',
    nameMaps: 'Jhon Jairo Acosta',
    tipoVehiculo: 'Carro',
    phone: '318 5573743',
  },
  {
    id: 34,
    name: 'Jhon Roman',
    nameMaps: 'John F Roman',
    tipoVehiculo: 'Carro',
    phone: '3125403263',
  },
  {
    id: 35,
    name: 'José Ancizar Velasquez Lopez',
    nameMaps: 'José Ancizar Velasquez Lopez',
    tipoVehiculo: 'Carro',
    phone: '3128801640',
  },
  {
    id: 36,
    name: 'Jose Edwin Alzate',
    nameMaps: 'Jose Edwin Alzate',
    tipoVehiculo: 'Moto',
    phone: '3108384439',
  },
  {
    id: 37,
    name: 'Jose Fernelly Sepulveda Marin',
    nameMaps: 'Jose Fernelly Sepulveda Marin',
    tipoVehiculo: 'Moto',
    phone: '3135565267',
  },
  {
    id: 38,
    name: 'Julian Vanegas',
    nameMaps: 'Julian Vanegas',
    tipoVehiculo: 'Moto',
    phone: '3012724799',
  },
  {
    id: 39,
    name: 'Juliana Quiceno',
    nameMaps: 'Juliana Quiceno',
    tipoVehiculo: 'Carro',
    phone: '3225257258',
  },
  {
    id: 40,
    name: 'Julio Dumar Arango',
    nameMaps: 'Julio Dumar Arango',
    tipoVehiculo: 'Carro',
    phone: '3183046016',
  },
  {
    id: 41,
    name: 'Luisa Maria Grajales Vargas',
    nameMaps: 'Luisa Maria Grajales Vargas',
    tipoVehiculo: 'Carro',
    phone: '3137245626',
  },
  {
    id: 42,
    name: 'Mauricio Lopez',
    nameMaps: 'Mauricio Lopez',
    tipoVehiculo: 'Moto',
    phone: '3008221570',
  },
  {
    id: 43,
    name: 'Nicolas Mora',
    nameMaps: 'Nicolas Mora',
    tipoVehiculo: 'Carro',
    phone: '3128187609',
  },
  {
    id: 44,
    name: 'Pedro Cardenas Colorado',
    nameMaps: 'Pedro Cardenas Colorado',
    tipoVehiculo: 'Carro',
    phone: '3186459987',
  },
  {
    id: 45,
    name: 'Walter Salazar Granados',
    nameMaps: 'Walter Salazar Granados',
    tipoVehiculo: 'Moto',
    phone: '3206556971',
  },
  {
    id: 46,
    name: 'Yime Hurtado Lopez',
    nameMaps: 'Yime Hurtado Lopez',
    tipoVehiculo: 'Carro',
    phone: '321 6531972',
  },
  {
    id: 47,
    name: 'Alejandro Racines Bolaños',
    nameMaps: 'Alejandro Racines Bolaños',
    tipoVehiculo: 'Carro',
    phone: '3206389262',
  },
];
