export const CONDUCTORES_POPA = [
  {
    id: 48,
    name: 'Luis Vanegas (Hijo)',
    nameMaps: 'Luis Vanegas (Hijo)',
    tipoVehiculo: 'CARRO',
    phone: '3122607123',
  },
  {
    id: 49,
    name: 'Dany ( Angelita )',
    nameMaps: 'Dany ( Angelita )',
    tipoVehiculo: 'CARRO',
    phone: '3106567203',
  },
  {
    id: 50,
    name: 'Hugo Lopez',
    nameMaps: 'Hugo Lopez',
    tipoVehiculo: 'CARRO',
    phone: '3175151454',
  },
  {
    id: 51,
    name: 'James Ramirez',
    nameMaps: 'James Ramirez',
    tipoVehiculo: 'CARRO',
    phone: '3128156844',
  },
  {
    id: 52,
    name: 'Alejandro Ossa',
    nameMaps: 'Normanyely Ramirez',
    tipoVehiculo: 'CARRO',
    phone: '3217208087',
  },
  {
    id: 53,
    name: 'Jorge Giraldo',
    nameMaps: 'Jorge Giraldo',
    tipoVehiculo: 'CARRO',
    phone: '3173784397',
  },
  {
    id: 54,
    name: 'Diego Fernando Valencia',
    nameMaps: 'Diego Fernando Valencia',
    tipoVehiculo: 'CARRO',
    phone: '3128725501',
  },
  {
    id: 55,
    name: 'Juan Camilo Lopez',
    nameMaps: 'Juan Camilo Lopez',
    tipoVehiculo: 'CARRO',
    phone: '3175151455',
  },
  {
    id: 56,
    name: 'Julian David Restrepo',
    nameMaps: 'Julian David Restrepo',
    tipoVehiculo: 'CARRO',
    phone: '3108223391',
  },
  {
    id: 57,
    name: 'Lubian Ramirez',
    nameMaps: 'JL Ramirez',
    tipoVehiculo: 'CARRO',
    phone: '3127088900',
  },
  {
    id: 58,
    name: 'Didier Valencia',
    nameMaps: 'Didier Valencia',
    tipoVehiculo: 'CARRO',
    phone: '3205528404',
  },
  {
    id: 59,
    name: 'Felipe Ramirez',
    nameMaps: 'Felipe Ramirez',
    tipoVehiculo: 'CARRO',
    phone: '3216207043',
  },
  {
    id: 60,
    name: 'Rodolfo Salazar',
    nameMaps: 'Rodolfo Salazar',
    tipoVehiculo: 'CARRO',
    phone: '3113691549',
  },
  {
    id: 61,
    name: 'Daniel Ramirez',
    nameMaps: 'Daniel Ramirez',
    tipoVehiculo: 'CARRO',
    phone: '3113550996',
  },
  {
    id: 62,
    name: 'Felipe Garcia',
    nameMaps: 'Felipe Garcia',
    tipoVehiculo: 'CARRO',
    phone: '3023444020',
  },
  {
    id: 63,
    name: 'Jhon Vairon',
    nameMaps: 'Jhon Byron Lopez',
    tipoVehiculo: 'CARRO',
    phone: '3216966363',
  },
  {
    id: 64,
    name: 'Adriana Arenas',
    nameMaps: 'Adriana Arenas',
    tipoVehiculo: 'CARRO',
    phone: '3104589643',
  },
  {
    id: 65,
    name: 'Juan Pablo Lopez',
    nameMaps: 'Juan Pablo Lopez',
    tipoVehiculo: 'CARRO',
    phone: '3154289638',
  },
  {
    id: 66,
    name: 'Luis Vanegas (Papá)',
    nameMaps: 'Luis Vanegas (Papá)',
    tipoVehiculo: 'CARRO',
    phone: '3106010450',
  },
  {
    id: 67,
    name: 'Jhonatan Morales',
    nameMaps: 'Jhonatan Morales',
    tipoVehiculo: 'CARRO',
    phone: '3104305831',
  },
  {
    id: 69,
    name: 'Robert Celis',
    nameMaps: 'Robert Celis',
    tipoVehiculo: 'CARRO',
    phone: '3142947619',
  },
  {
    id: 70,
    name: 'Giovany Yara',
    nameMaps: 'Giovany Yara',
    tipoVehiculo: 'CARRO',
    phone: '3185234507',
  },
  {
    id: 71,
    name: 'Sebastian Valos (Provenza)',
    nameMaps: 'Sebastian Valos (Provenza)',
    tipoVehiculo: 'CARRO',
    phone: '3148389509',
  },
  {
    id: 72,
    name: 'Kevin Garcia',
    nameMaps: 'Kevin Garcia',
    tipoVehiculo: 'CARRO',
    phone: '3207259197',
  },
  {
    id: 73,
    name: 'Miryam Rodriguez',
    nameMaps: 'Miryam Rodriguez',
    tipoVehiculo: 'CARRO',
    phone: '3016187652',
  },
  {
    id: 74,
    name: 'Alex Tabima',
    nameMaps: 'Alex Tabima',
    tipoVehiculo: 'MOTO',
    phone: '3117828680',
  },
  {
    id: 75,
    name: 'Alex Salazar',
    nameMaps: 'Alexander Salazar',
    tipoVehiculo: 'MOTO',
    phone: '3155101111',
  },
  {
    id: 76,
    name: 'Cristian Chavarro',
    nameMaps: 'Cristian Chavarro',
    tipoVehiculo: 'MOTO',
    phone: '3127455842',
  },
  {
    id: 77,
    name: 'Holanda Santa',
    nameMaps: 'Holanda Santa',
    tipoVehiculo: 'MOTO',
    phone: '3113477680',
  },
  {
    id: 78,
    name: 'Genaro Vargas',
    nameMaps: 'Genaro Vargas',
    tipoVehiculo: 'MOTO',
    phone: '3206254765',
  },
  {
    id: 79,
    name: 'Hernan Manyoma',
    nameMaps: 'Hernan Lobon Manyoma',
    tipoVehiculo: 'MOTO',
    phone: '3215714308',
  },
  {
    id: 80,
    name: 'Kevin Diez',
    nameMaps: 'Kevin Diez',
    tipoVehiculo: 'MOTO',
    phone: '3203118792',
  },
  {
    id: 81,
    name: 'Oscar Calvo',
    nameMaps: 'Oscar Calvo',
    tipoVehiculo: 'MOTO',
    phone: '3146419242',
  },
  {
    id: 82,
    name: 'Adrian Vasco',
    nameMaps: 'Adrian Vasco',
    tipoVehiculo: 'MOTO',
    phone: '3136572175',
  },
  {
    id: 83,
    name: 'Mauricio Jimenez',
    nameMaps: 'Mauricio Jimenez',
    tipoVehiculo: 'MOTO',
    phone: '3204029485',
  },
  {
    id: 84,
    name: 'Carlos Upegui',
    nameMaps: 'Carlos Upegui',
    tipoVehiculo: 'MOTO',
    phone: '3193704376',
  },
  {
    id: 85,
    name: 'Sergio Zuleta',
    nameMaps: 'Sergio Zuleta',
    tipoVehiculo: 'MOTO',
    phone: '3108383138',
  },
  {
    id: 86,
    name: 'Luis Bertel',
    nameMaps: 'Luis Bertel',
    tipoVehiculo: 'MOTO',
    phone: '3147995892',
  },
  {
    id: 87,
    name: 'Luis Carlos Rodas',
    nameMaps: 'Luis Rodas',
    tipoVehiculo: 'MOTO',
    phone: '3208102210',
  },
  {
    id: 88,
    name: 'David Mejia',
    nameMaps: 'David Mejia',
    tipoVehiculo: 'MOTO',
    phone: '3217574347',
  },
  {
    id: 89,
    name: 'Edwin Jimenez',
    nameMaps: 'Edwin Jimenez',
    tipoVehiculo: 'MOTO',
    phone: '3504351811',
  },
  {
    id: 90,
    name: 'Marina Gomez',
    nameMaps: 'Marina Gomez',
    tipoVehiculo: 'MOTO',
    phone: '3128309694',
  },
  {
    id: 91,
    name: 'Jorge Andres',
    nameMaps: 'Jorge Andres Izaza Hernandez',
    tipoVehiculo: 'MOTO',
    phone: '3145908442',
  },
  {
    id: 92,
    name: 'Juan Sebastian Morales',
    nameMaps: 'Juan Sebastian Morales',
    tipoVehiculo: 'MOTO',
    phone: '3215344446',
  },
  {
    id: 93,
    name: 'Tiffany Juliana Bedoya',
    nameMaps: 'Tiffany Juliana Bedoya',
    tipoVehiculo: 'MOTO',
    phone: '3225602324',
  },
  {
    id: 94,
    name: 'Julian Forero',
    nameMaps: 'Julian Forero',
    tipoVehiculo: 'MOTO',
    phone: '3154438949',
  },
  {
    id: 95,
    name: 'Jhon Jairo Quintero',
    nameMaps: 'Jhon Jairo Quintero',
    tipoVehiculo: 'MOTO',
    phone: '3136329838',
  },
  {
    id: 96,
    name: 'Ricardo Iglesia',
    nameMaps: 'Ricardo Iglesia',
    tipoVehiculo: 'MOTO',
    phone: '3223578423',
  },
  {
    id: 97,
    name: 'Humberto Castañeda',
    nameMaps: 'Humberto Castañeda',
    tipoVehiculo: 'MOTO',
    phone: '3225580654',
  },
  {
    id: 98,
    name: 'Carlos Rivera',
    nameMaps: 'Carlos Rivera',
    tipoVehiculo: 'MOTO',
    phone: '3166060686',
  },
  {
    id: 99,
    name: 'Carlos Andres Bedoya',
    nameMaps: 'Carlos Andres Bedoya',
    tipoVehiculo: 'CARRO',
    phone: '',
  },
  {
    id: 100,
    name: 'Gustavo Velasquez',
    nameMaps: 'Gustavo Velasquez',
    tipoVehiculo: 'CARRO',
    phone: '',
  },
  {
    id: 101,
    name: 'Marta Gallego',
    nameMaps: 'Marta Gallego',
    tipoVehiculo: 'CARRO',
    phone: '3147301912',
  },
  {
    id: 102,
    name: 'David Clinton',
    nameMaps: 'David Clinton',
    tipoVehiculo: 'MOTO',
    phone: '3137405777',
  },
  {
    id: 103,
    name: 'Juan Camilo Lopez',
    nameMaps: 'Juan Camilo Lopez',
    tipoVehiculo: 'CARRO',
    phone: '3187348963',
  },
  {
    id: 104,
    name: 'Nathalia Gañan',
    nameMaps: 'Nathalia Gañan',
    tipoVehiculo: 'CARRO',
    phone: '3136272813',
  },
  {
    id: 105,
    name: 'Luis Albeiro Garcia',
    nameMaps: 'Luis Albeiro Garcia',
    tipoVehiculo: 'CARRO',
    phone: '3127739390',
  },
  {
    id: 106,
    name: 'Luz Marina Lopez',
    nameMaps: 'Luz Marina Lopez',
    tipoVehiculo: 'CARRO',
    phone: '3157820016',
  },
  {
    id: 107,
    name: 'Normanyely Ramirez',
    nameMaps: 'Normanyely Ramirez',
    tipoVehiculo: 'Carro',
    phone: '3145566808',
  },
  {
    id: 109,
    name: 'Viviana Ramirez',
    nameMaps: 'Viviana Ramirez',
    tipoVehiculo: 'CARRO',
    phone: '3116014191',
  },
  {
    id: 110,
    name: 'Lumar Ramirez',
    nameMaps: 'Lumar Ramirez',
    tipoVehiculo: 'CARRO',
    phone: '3147180441',
  },
  {
    id: 111,
    name: 'Martha Cecilia Gallego',
    nameMaps: 'Martha Cecilia Gallego',
    tipoVehiculo: 'CARRO',
    phone: '3147301912',
  },
  {
    id: 112,
    name: 'JOSE CASAS',
    nameMaps: 'JOSE CASAS',
    tipoVehiculo: 'CARRO',
    phone: '3224303862',
  },
  {
    id: 113,
    name: 'DAVID MONTES',
    nameMaps: 'DAVID MONTES',
    tipoVehiculo: 'MOTO',
    phone: '3234928607',
  },
  {
    name: 'Tiffany Juliana Bedoya',
    nameMaps: 'Tiffany Juliana Bedoya',
    tipoVehiculo: 'MOTO',
    phone: '3225602324',
  },
  {
    name: 'Viviana Ramirez',
    nameMaps: 'Viviana Ramirez',
    tipoVehiculo: 'CARRO',
    phone: '3116014191',
  },
  {
    name: 'JHON JAMES ZULUAGA',
    nameMaps: 'JHON JAMES ZULUAGA',
    tipoVehiculo: 'CARRO',
    phone: '3116460891',
  },
  {
    name: 'HERNANDO COLORADO',
    nameMaps: 'HERNANDO COLORADO',
    tipoVehiculo: 'CARRO',
    phone: '3104749302',
  },
  {
    name: 'DAVID GIRALDO',
    nameMaps: 'DAVID GIRALDO',
    tipoVehiculo: 'MOTO',
    phone: '3137405777',
  },
  {
    name: 'DIEGO ALEJANDRO HENAO',
    nameMaps: 'DIEGO ALEJANDRO HENAO',
    tipoVehiculo: 'MOTO',
    phone: '3186113050',
  },
  {
    name: 'LUIS VANEGAS (HIJO)',
    nameMaps: 'LUIS VANEGAS (HIJO)',
    tipoVehiculo: 'CARRO',
    phone: '3122607123',
  },
  {
    name: 'Sebastian Ramirez',
    nameMaps: 'sebastian ramirez',
    tipoVehiculo: 'CARRO',
    phone: '3114211186',
  },
  {
    name: 'Fernando Valencia',
    nameMaps: 'sebastian ramirez',
    tipoVehiculo: 'CARRO',
    phone: '3114211186',
  },
];
